const lessons=[['Home Row','asdf jkl;','asdf jkl; asdf jkl; dad sad fall ask'],['Top Row','qwerty uiop','red tree quiet type power'],['Bottom Row','zxcv bnm','van zoom mix cabin'],['Shift & Capitals','Shift + letters','Big Change Students Type Well.'],['Numbers','1234567890','2026 123 456 7890'],['Punctuation','.,!?;:','Hello, student! Type well; stay calm.'],['Sentences','All keys','Practice makes typing feel natural.']];
const passages={easy:lessons[0][2],medium:'The quick student learns to type with calm hands and steady rhythm.',hard:'Accuracy comes first; speed follows when good keyboard habits become automatic.'};
const challengeText='Practice makes progress. Keep your hands calm and your eyes on the screen. Good typing starts with accuracy. BigChange students learn one key at a time. Speed grows naturally when correct habits become automatic. Keep going and do your best. ';
const PASS_ACCURACY=90;let level='easy',session=null,timer=null,currentLesson=0,challengeMode=false,challengeSeconds=60,challengeRunning=false;
const $=s=>document.querySelector(s);let state={};try{state=JSON.parse(localStorage.getItem('bc-keyboard')||'{}')||{}}catch{state={}}state.completed=Array.isArray(state.completed)?[...new Set(state.completed.filter(i=>Number.isInteger(i)&&i>=0&&i<lessons.length))]:[];
function save(){try{localStorage.setItem('bc-keyboard',JSON.stringify(state))}catch{}}
function stopTypingTimer(){if(timer)clearInterval(timer);timer=null;challengeRunning=false}
function show(id){stopTypingTimer();document.dispatchEvent(new CustomEvent('bc:viewchange',{detail:{id}}));document.querySelectorAll('.view').forEach(v=>v.style.display=v.id===id?'block':'none');if(id==='progress')renderProgress()}window.show=show;document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const id=b.dataset.view;if(id==='practice'){challengeMode=false;level='easy';passages.easy=lessons[currentLesson][2];$('#practice-heading').textContent=`Practice: ${lessons[currentLesson][0]}`;document.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('active',x.dataset.level==='easy'));show('practice');start();return}challengeMode=false;show(id)});
$('#save-profile').onclick=()=>{state.name=$('#student-name').value.trim()||'Student';save();$('#profile').style.display='none';$('#student-nav').style.display='grid';$('#welcome').textContent=`Welcome, ${state.name}. Choose Learn to begin.`;show('learn')};if(state.name){$('#student-name').value=state.name;$('#profile').style.display='none';$('#student-nav').style.display='grid';$('#welcome').textContent=`Welcome back, ${state.name}. Keep building your keyboard skills.`}else{$('#student-nav').style.display='none'}
function renderLessons(){$('#lesson-list').innerHTML=lessons.map((l,i)=>`<button class="lesson ${state.completed.includes(i)?'done':''}" data-lesson="${i}"><strong>${i+1}. ${l[0]}</strong><span>${l[1]}</span>${state.completed.includes(i)?'<em>✓ Complete</em>':''}</button>`).join('');document.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{challengeMode=false;currentLesson=+b.dataset.lesson;level='easy';passages.easy=lessons[currentLesson][2];$('#practice-heading').textContent=`Practice: ${lessons[currentLesson][0]}`;show('practice');start()})}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function visibleChar(c,wrong=false){if(c===' ')return wrong?'␠':'&nbsp;';return esc(c)}
function renderReference(){if(!session)return;let html='';for(let i=0;i<session.text.length;i++)html+=`<span class="${i===session.pos&&!session.done?'reference-current':''}">${visibleChar(session.text[i])}</span>`;$('#target').innerHTML=html}
function renderTyped(){if(!session)return;let html='';for(let i=0;i<session.pos;i++)html+=`<span class="typed-correct">${visibleChar(session.typedChars[i])}</span>`;if(session.states[session.pos]===KQ.WRONG)html+=`<span class="typed-wrong">${visibleChar(session.typedChars[session.pos],true)}</span>`;$('#typed-display').innerHTML=html||'<span class="typing-placeholder">Start typing here…</span>'}
function updateTimer(){$('#timer-seconds').textContent=challengeSeconds}
function start(){stopTypingTimer();session=new KQ.TypingSession(challengeMode?challengeText.repeat(8):passages[level]);challengeSeconds=60;updateTimer();$('#challenge-timer').hidden=!challengeMode;$('.levels').style.display=challengeMode?'none':'flex';$('#start').textContent=challengeMode?'Restart Challenge':'Restart Practice';$('#message').textContent=challengeMode?'Ready — timer starts with your first key.':'';render();$('#typed-display').focus()}
function startChallengeClock(){if(!challengeMode||challengeRunning||!session||session.done)return;challengeRunning=true;timer=setInterval(()=>{challengeSeconds=Math.max(0,challengeSeconds-1);updateTimer();if(challengeSeconds===0)finishChallenge()},1000)}
function finishChallenge(){if(!session||session.challengeResultHandled)return;stopTypingTimer();if(!session.done)session.finish();session.challengeResultHandled=true;const r=session.stats(),best=state.best||{wpm:0,accuracy:0};if(r.wpm>best.wpm||(r.wpm===best.wpm&&r.accuracy>best.accuracy))state.best={wpm:r.wpm,accuracy:r.accuracy};state.last={wpm:r.wpm,accuracy:r.accuracy};save();$('#message').textContent=`Time! ${r.wpm} WPM · ${r.accuracy}% accuracy`;render();renderProgress()}
function finishPractice(){const s=session.stats();state.last={wpm:s.wpm,accuracy:s.accuracy};if(s.accuracy>=PASS_ACCURACY){$('#message').textContent=`Practice complete — ${s.accuracy}% accuracy!`;if(level==='easy'&&!state.completed.includes(currentLesson))state.completed.push(currentLesson)}else{$('#message').textContent=`Try again — ${s.accuracy}% accuracy. Aim for ${PASS_ACCURACY}% or better.`}save();renderLessons()}
function render(){if(!session)return;const s=session.stats();renderReference();renderTyped();$('#wpm').textContent=s.wpm;$('#accuracy').textContent=s.accuracy+'%';$('#mistakes').textContent=s.mistakes;if(s.done&&challengeMode&&!session.challengeResultHandled){finishChallenge();return}if(s.done&&!challengeMode&&!session.resultHandled){session.resultHandled=true;stopTypingTimer();finishPractice()}}
document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{challengeMode=false;level=b.dataset.level;document.querySelectorAll('[data-level]').forEach(x=>x.classList.toggle('active',x===b));start()});
document.addEventListener('keydown',e=>{if(!session||session.done||$('#practice').style.display!=='block')return;if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='Backspace'){e.preventDefault();session.backspace();$('#message').textContent='';render();return}if(e.key.length===1){e.preventDefault();const expected=session.expected;if(challengeMode&&!challengeRunning)startChallengeClock();const result=session.input(e.key);if(!challengeMode&&result!=='complete')$('#message').textContent=result==='wrong'?`Mistake: ${e.key===' '?'Space':e.key}. Expected ${expected===' '?'Space':expected}. Press Backspace to correct it.`:result==='locked'?'Press Backspace to clear the red key, then type the correct key.':'';render()}});
$('#start').onclick=start;function renderProgress(){const n=state.completed.length;$('#progress-content').innerHTML=`<p><strong>${n} of ${lessons.length} lessons completed</strong></p><progress value="${n}" max="${lessons.length}"></progress><p>${state.last?`Last result: ${state.last.wpm} WPM · ${state.last.accuracy}% accuracy`:'Complete a lesson to record your first result.'}</p>${state.best?`<p>Best 1-minute challenge: <strong>${state.best.wpm} WPM · ${state.best.accuracy}%</strong></p>`:''}`;if(state.best){$('#best-wpm').textContent=state.best.wpm;$('#best-accuracy').textContent=state.best.accuracy+'%'}}
$('#challenge-start').onclick=()=>{challengeMode=true;level='hard';show('practice');$('#practice-heading').textContent='1-Minute Challenge';start()};renderLessons();renderProgress();if(state.name){show('learn')}else{document.querySelectorAll('.view').forEach(v=>v.style.display='none')}